### ISSUE TITLE
Functionality Split: Completing vs Deleting

### ISSUE THREAD

**Issue by paleym** [DotDashh/HelpTickets#1]
Hello,

Would be nice to have a differentiation between completing a ticket and deleting it.  I would like to have two different nodes, so that my mods can complete but not delete and my admins can delete them.

This might lead to either having two lists, one for 'active' and 'completed' tickets, or having another column in /ticket list that says whether it has been completed or not.

Thanks.

**Comment by ItsDoot** [comment]
Completed for [v1.1.0](https://github.com/DotDashh/HelpTickets/releases/tag/1.1.0).

**Comment by paleym** [comment]
Would it be possible to just split the delete / complete stuff so it's two commands?
